### PR TITLE
Layers Panel: make icons darker on hover

### LINKED ISSUE #9544: Layer Panel: Hover state of icons when a layer is selected
## Bug Description

Layer Panel: The hover color of the icons when a layer is selected is too dark. @agingoldseco would like us to lighten it up a little.

- [x] Color TBD

## Expected Behaviour

Change the hover color of the icons when the layer is selected

## Steps to Reproduce

1. click a layer in the layer panel
2. Hover an icon like `delete` or `copy` on that layer

## Screenshots

image

## Additional Context

- Plugin Version: 1.14.0-alpha
- WordPress Version: 5.8.1
- Operating System: Mac OSX Sierra
- Browser: Chrome

### PR DESCRIPTION
**Pull request by BrookeGraham**
## Context

Layer Panel: The hover color of the icons when a layer is selected is too dark.

## Summary

@agingoldseco would like gray 70 to be used 

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Hover the trash can icon after selecting a layer within the layers panel. 
2. Notice it is no longer quite as dark as before

### New:
Screen Shot 2021-10-29 at 1 32 26 PM

### Old: 

Screen Shot 2021-10-29 at 10 19 05 AM
### Does this PR change what data or activity we track or use?
no

### Does this PR have a legal-related impact?
no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9544

### CODE REVIEW

File: packages/story-editor/src/components/panels/design/layer/layer.js [hunk 1]
```diff
@@ -208,7 +208,7 @@ const LayerAction = styled(Button).attrs({
   }
 
   /*
-   * override base button background color so we can receive the 
+   * override base button background color so we can receive the
```
Comment (BrookeGraham) [inline packages/story-editor/src/components/panels/design/layer/layer.js]: linter

**Review by BrittanyIRL — APPROVED** [review]
🦖

**Review by samwhale — APPROVED** [review]
✨

**Review by maxyinger — APPROVED** [review]
