### PR TITLE
Fix Page Templates usage

### LINKED ISSUE #9294: Choosing Saved Templates in the Page Templates panel crashes the editor
## Expected Behaviour
Saved Templates should open instead of the editor crashing.

## Steps to Reproduce
1. Open the Page Templates tab
2. Choose "Saved Templates" from the dropdown
3. See the editor crashing

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

It was reported by us and also by users that the "Saved Templates" function is broken in the last release due to [multiple bugs](https://github.com/google/web-stories-wp/issues/9294#issuecomment-936609703).

## Summary

Since this is actually three bugs in one, this PR contains some JavaScript changes but also some PHP changes.

In essence, it makes saving custom page templates work again.

See below for details.

## Relevant Technical Choices

**Note:** see also individual commits for a better understanding.

**Don't fetch page templates if `nextTemplatesToFetch` is `false`**

This is self-explanatory. Basically, this would lead to REST API requests being made with `?page=false`, which will be rejected by the API because `false` clearly is not an `integer`.

**Ensure `TemplateList` doesn't crash when `pages` is `null`**

This is self-explanatory. `pages` is always `null` at the beginning. And when REST API fetching fails, it will stay `null`. However, the component didn't support this and crashed when `pages` wasn't an array. So this adds some extra hardening.

**Always show `TemplateSave` button**

Again, self-explanatory. Always show the button - even if templates haven't been loaded yet.

**Improve service registration to ensure correct order**

This change allows us to clearly define dependencies between services using `HasRequirements`, without having to use different action priorities at the same time.

**Example:** `Settings`, `Story_Post_Type` and `Page_Template_Post_Type` are all delayed to be registered on `init`, with priority 10.

However, because `Story_Post_Type` depends on `Settings`, it will have priority 11 to ensure it runs after.

And because `Page_Template_Post_Type` depends on `Story_Post_Type`, it will have new priority 12 to ensure the `Story_Post_Type` service is properly registered first.

This, together with extended usage of `HasRequirements` throughout the code base makes dependency resolution more robust.

**Remove unnecessary abstraction for REST controllers**

`Autosaves_Controller` and `Lock_Controller` were both abstract classes, theoretically making it easier to implement them for multiple post types. However, there are no plans for ever using those for any post types other than web-story, so having abstract classes is overkill.

The code has been merged into `Stories_Autosaves_Controller` and `Stories_Lock_Controller`, respectively.

**E2E tests**

To prevent regressions, this PR adds an e2e test verifying that custom page templates can be loaded & saved.

## To-do

N/A

## User-facing changes

* The "Save page as template" button now doesn't have a hover effect when disabled
* The "Saved Templates" panel is no longer broken

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Create a new story
1. Go to page templates tab
2. Verify that the "Save page as template" button is disabled
3. Add an element to the page
4. Verify that the button is no longer disabled and allows you to create a new page template

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9294

### CODE REVIEW

**Review by BrittanyIRL — COMMENTED** [review]
Running this locally after a fresh install and I think something is missing for the `POST` route when trying to save a current page as a template. I'm getting a 404 response. Post route looks like this: `http://localhost:8899/wp-json/web-stories/v1/web-story-page//?_locale=user` so that 404 makes sense :) 

Also tagging Miina since Prometheus implemented this originally and she should have context for this update as well.

**Comment by swissspidy** [comment]
> Running this locally after a fresh install and I think something is missing for the `POST` route when trying to save a current page as a template. I'm getting a 404 response. Post route looks like this: `http://localhost:8899/wp-json/web-stories/v1/web-story-page//?_locale=user` so that 404 makes sense :)
> 
> Also tagging Miina since Prometheus implemented this originally and she should have context for this update as well.

Yeah one of my later refactorings broke it again, re-fixing it right now.

File: packages/story-editor/src/components/library/panes/pageTemplates/templateSave.js [hunk 1]
```diff
@@ -143,21 +144,17 @@ function TemplateSave({ setShowDefaultTemplates, updateList }) {
     ]
   );
 
-  const textId = useMemo(() => `template_save_btn_${uuidv4()}`, []);
   return (
     <SaveButton
       aria-disabled={isDisabled}
       onClick={handleSaveTemplate}
-      aria-labelledby={textId}
```
Comment (miina) [inline packages/story-editor/src/components/library/panes/pageTemplates/templateSave.js:151]: Curious why switch from using labelled by to `aria-label`?

File: packages/story-editor/src/components/library/panes/pageTemplates/pageTemplatesPane.js [hunk 2]
```diff
@@ -151,14 +162,12 @@ function PageTemplatesPane(props) {
...
         <>
-          {savedTemplates && (
-            <ButtonWrapper>
-              <TemplateSave
-                setShowDefaultTemplates={setShowDefaultTemplates}
-                updateList={updateTemplatesList}
-              />
-            </ButtonWrapper>
-          )}
+          <ButtonWrapper>
```
Comment (miina) [inline packages/story-editor/src/components/library/panes/pageTemplates/pageTemplatesPane.js:165]: I think that clicking on the button before the `savedTemplates` has been loaded will result in a failure, that's why it was hidden originally. Perhaps we should just disable it then? Since adding a new template relies on the array existing.

E.g. if I quickly click on the button after switching to the tab, I get this error:
Screenshot 2021-10-07 at 12 21 26

Trying again works though and it's unlikely that someone would click on it very quickly, but it might happen in case of slow connection. Thoughts?

**Review by miina — APPROVED** [review]
Had 2 questions, generally LGTM and works well, too (didn't review PHP).

**Comment by miina** [comment]
@swissspidy FYI I'm seeing an unrelated console error when actually adding a new page template with images:

Screenshot 2021-10-07 at 12 31 20
Screenshot 2021-10-07 at 12 30 50

Is this something you remember seeing before, or needs a new issue?

File: packages/story-editor/src/components/library/panes/pageTemplates/templateSave.js (hunk 1 above)
Comment (swissspidy) [reply packages/story-editor/src/components/library/panes/pageTemplates/templateSave.js:151]: This is a `button` element, for which its value already is the label.

There is simply no need to use `aria-labelledby` for a button.

Probably don't even need `aria-label` and just can use the label below, but then we'd probably need `aria-hidden` on the `svg` since its decorative.

File: packages/story-editor/src/components/library/panes/pageTemplates/pageTemplatesPane.js (hunk 2 above)
Comment (swissspidy) [reply packages/story-editor/src/components/library/panes/pageTemplates/pageTemplatesPane.js:165]: Ah, that's a good point. Yeah disabling when it's still null and not an array makes sense.

File: includes/REST_API/Autosaves_Controller.php [hunk 3]
```diff
@@ -1,221 +0,0 @@
-<?php
```
Comment (spacedmonkey) [inline includes/REST_API/Autosaves_Controller.php:1]: Why is this class being removed?

File: includes/REST_API/Publisher_Logos_Controller.php [hunk 4]
```diff
@@ -50,18 +51,40 @@ class Publisher_Logos_Controller extends REST_Controller {
...
+	 * Get the list of service IDs required for this service to be registered.
+	 *
+	 * Needed because the story post type needs to be registered first.
+	 *
+	 * @since 1.13.0
+	 *
+	 * @return string[] List of required services.
+	 */
+	public static function get_requirements(): array {
+		return [ 'story_post_type' ];
```
Comment (spacedmonkey) [inline includes/REST_API/Publisher_Logos_Controller.php]:
```suggestion
		return [ 'settings', 'story_post_type' ];
```

File: includes/REST_API/Stories_Lock_Controller.php [hunk 5]
```diff
@@ -24,22 +24,380 @@
...
+
+	/**
+	 * Delete post lock
+	 *
+	 * @since 1.6.0
+	 *
+	 * @param WP_REST_Request $request Full details about the request.
+	 * @return WP_REST_Response Response object on success.
+	 */
+	public function delete_item( $request ): WP_REST_Response {
```
Comment (spacedmonkey) [inline includes/REST_API/Stories_Lock_Controller.php:177]:
```suggestion
	public function delete_item( WP_REST_Request  $request ): WP_REST_Response {
```

File: includes/REST_API/Stories_Lock_Controller.php [hunk 6]
```diff
@@ -24,22 +24,380 @@
...
+		return $response;
+	}
+
+	/**
+	 * Get the lock, if the ID is valid.
+	 *
+	 * @param int $post_id Supplied ID.
+	 * @return array|false Lock as string or default to false.
+	 */
+	protected function get_lock( $post_id ) {
```
Comment (spacedmonkey) [inline includes/REST_API/Stories_Lock_Controller.php]:
```suggestion
	protected function get_lock( int $post_id ) {
```

File: includes/REST_API/Autosaves_Controller.php (hunk 3 above)
Comment (swissspidy) [reply includes/REST_API/Autosaves_Controller.php:1]: See PR description.

File: includes/REST_API/Stories_Lock_Controller.php (hunk 6 above)
Comment (swissspidy) [reply includes/REST_API/Stories_Lock_Controller.php]: FWIW this is not newly introduced code, just moved code. But yeah I suppose we can add this.

File: includes/Infrastructure/ServiceBasedPlugin.php [hunk 7]
```diff
@@ -475,16 +541,18 @@ protected function get_identifier_from_fqcn( $fqcn ): string {
...
 				$this->maybe_register_service( $id, $class );
 			} else {
 				add_action(
-					$registration_action,
+					$action,
 					function () use ( $id, $class ) {
 						$this->maybe_register_service( $id, $class );
-					}
+					},
+					$priority
```
Comment (spacedmonkey) [inline includes/Infrastructure/ServiceBasedPlugin.php:555]: I wonder why this was missing?

File: includes/REST_API/Stories_Lock_Controller.php (hunk 5 above)
Comment (swissspidy) [reply includes/REST_API/Stories_Lock_Controller.php:177]: This is not possible ⚠️ 

This is incompatible with the method declaration in the parent class.

**Comment by spacedmonkey** [comment]
Created a follow up issue from this PR, as it opens up some great options https://github.com/google/web-stories-wp/issues/9316

File: includes/REST_API/Stories_Lock_Controller.php (hunk 5 above)
Comment (spacedmonkey) [reply includes/REST_API/Stories_Lock_Controller.php:177]: 😢

File: includes/Infrastructure/ServiceBasedPlugin.php [hunk 8]
```diff
@@ -284,7 +284,6 @@ public function register_services() {
 				&&
 				! $this->requirements_are_met( $id, $class, $services )
 			) {
-				next( $services );
```
Comment (spacedmonkey) [inline includes/Infrastructure/ServiceBasedPlugin.php:287]: Why was this line removed?

File: tests/phpunit/integration/tests/REST_API/Publisher_Logos_Controller.php [hunk 9]
```diff
@@ -90,7 +91,10 @@ public static function wpSetUpBeforeClass( $factory ) {
 	public function set_up() {
 		parent::set_up();
 
-		$this->controller = new \Google\Web_Stories\REST_API\Publisher_Logos_Controller( new Settings() );
+		$this->controller = new \Google\Web_Stories\REST_API\Publisher_Logos_Controller(
+			new Settings(),
+			new \Google\Web_Stories\Story_Post_Type( new Settings() )
+		);
```
Comment (spacedmonkey) [inline tests/phpunit/integration/tests/REST_API/Publisher_Logos_Controller.php]:
```suggestion
		$settings         = new Settings();
		$this->controller = new \Google\Web_Stories\REST_API\Publisher_Logos_Controller(
			$settings,
			new \Google\Web_Stories\Story_Post_Type( $settings )
		);
```

File: includes/Infrastructure/ServiceBasedPlugin.php (hunk 8 above)
Comment (swissspidy) [reply includes/Infrastructure/ServiceBasedPlugin.php:287]: See https://github.com/ampproject/amp-wp/pull/6529 and also https://github.com/ampproject/amp-wp/pull/6529

**Comment by spacedmonkey** [comment]
Question: Would remove the delayed interface on some of the services help here? For example, not delay the settings service at all.

**Comment by swissspidy** [comment]
> Question: Would remove the delayed interface on some of the services help here? For example, not delay the settings service at all.

I don't think it would help. Especially not with this current PR.

If you remove `Delayed`, `Settings::register()` would need to be updated to only register options on `init` (with some priority, e.g. 10).

That does mean the `Story_Post_Type` class for instance gets a valid `Settings` instance which has been registered, but the _options_ might not have necessarily been registered yet (because `Story_Post_Type` could be hooked to a higher, prio, e.g. 5.

So that would actually be quite dangerous.

**Comment by swissspidy** [comment]
> @swissspidy FYI I'm seeing an unrelated console error when actually adding a new page template with images:
> 
> Screenshot 2021-10-07 at 12 31 20
> 
> Screenshot 2021-10-07 at 12 30 50
> 
> Is this something you remember seeing before, or needs a new issue?

This needs a separate ticket issue for sure. I do remember talking about adding proper `catch` to `preloadImage` in the past.

File: packages/story-editor/src/components/library/panes/pageTemplates/pageTemplatesPane.js (hunk 2 above)
Comment (swissspidy) [reply packages/story-editor/src/components/library/panes/pageTemplates/pageTemplatesPane.js:165]: Found a better solution, just fixing `updateTemplatesList`

**Review by BrittanyIRL — APPROVED** [review]
working for me - js looks good, you don't want me to review the PHP. 😅

**Comment by miina** [comment]
> This needs a separate ticket issue for sure. I do remember talking about adding proper catch to preloadImage in the past.

Added https://github.com/google/web-stories-wp/issues/9326

File: includes/Infrastructure/ServiceBasedPlugin.php (hunk 7 above)
Comment (swissspidy) [reply includes/Infrastructure/ServiceBasedPlugin.php:555]: The whole priority thing seemed like not fully implemented when I worked on this PR. But alas 🤷

**Review by spacedmonkey — APPROVED** [review]
