### PR TITLE
Output: Ensure `<amp-story-page-outlink>` is always the last child

### LINKED ISSUE #9513: Video Captions: `<amp-story-page-outlink>` not last child anymore
## Bug Description

The new captions feature currently prints captions as the last child of `<amp-story-page>`.

That causes AMP validation errors if there is a page attachment on the same page, because `<amp-story-page-outlink>` must be the last child.

## Expected Behaviour

- No AMP validation error anymore
- `<amp-story-page-outlink>` is last child

## Steps to Reproduce

1. Add page attachment and video with captions on the same page
2. Validate story

## Additional Context

- Plugin Version: 1.13.0
- WordPress Version: 5.8
- Operating System: macOS
- Browser: Chrome

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

The new captions feature currently prints captions as the last child of `<amp-story-page>`, which causes AMP validation errors.

## Summary

This PR changes the story markup generation to ensure <amp-story-page-outlink>` is always the last child of `<amp-story-page>`.

## Relevant Technical Choices

Adds a PHP sanitizer to fix existing stories.

## To-do

N/A

## User-facing changes

N/A

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Add page attachment and video with captions on the same page
1. Validate story
2. Don't see validation error for `amp-story-page-outlink`

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9513

### CODE REVIEW

File: packages/story-editor/src/output/page.js [hunk 1]
```diff
@@ -167,6 +156,17 @@ function OutputPage({
           </div>
         </amp-story-grid-layer>
       )}
+      {hasPageAttachment && (
```
Comment (miina) [inline packages/story-editor/src/output/page.js:160]: Should we add a comment here to keep this as the last element for future issues, even though it now has the sanitizer, would still be nice to keep it in the correct place.

**Review by miina — APPROVED** [review]
Looks like some tests/linters are failing now, otherwise LGTM!

File: packages/story-editor/src/output/page.js (hunk 1 above)
Comment (swissspidy) [reply packages/story-editor/src/output/page.js:160]: There is also a test ensuring this. But can't hurt. Comment added.
