### PR TITLE
Taxonomy: Add placeholder text and update heading level

### LINKED ISSUE #9271: Taxonomy: Border Separation Missing
## Bug Description

There's supposed to be a border between taxonomy sections, like this in figma: https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor-Sprint-Feature-Level-Designs_?node-id=9721%3A383439 

## Expected Behaviour

There should be borders between taxonomies in the taxonomy panel for every section except the last one.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### LINKED ISSUE #9272: Taxonomy: Most Used Heading Level
## Bug Description

'Most Used' section of tags should be a level 4 heading not level 3. 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### LINKED ISSUE #9300: Taxonomy: Give Hierarchical Search Input a Placeholder
This is a hold over until we can unify our search inputs in the editor. Let's start by giving the search input on hierarchical components a placeholder - can use the name that comes from the `taxonomy.labels` to make sure it stays accurate for whatever custom taxonomies a user might have. 

Update 10.6.2021 3pm MST - additional request made to add the 'search' icon to make this search input look more like others in the editor instead of like Gutenberg.

(created from #9285 )

### PR DESCRIPTION
**Pull request by maxyinger**
## Context
Found in most recent bug bash

## Summary
Adds a border between `Categories` & `Tags` section

## Relevant Technical Choices
Didn't use the `taxonomy.labels.search_item` for the search placeholder cus it would be too repetitive and specific for a placeholder. instead just used the agnostic action name `search`.

## To-do
NA

## User-facing changes
Adds a border between `Categories` & `Tags` section and a placeholder for the Category search input
Screen Shot 2021-10-06 at 2 14 55 PM

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Go to Editor -> Document Tab -> Categories & Tags Panel
2. See that there is now a border between `Category` and `Tag` inputs
3. See that the Categories search input has a placeholder of `search`

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9272
Fixes #9271 
Fixes #9300

### CODE REVIEW

File: packages/story-editor/src/components/panels/document/taxonomies/HierarchicalTermSelector.js [hunk 1]
```diff
@@ -230,62 +235,66 @@ function HierarchicalTermSelector({
...
-                >
-                  {__('Cancel', 'web-stories')}
-                </AddNewCategoryButton>
-              </ButtonContainer>
-            </AddNewCategoryForm>
-          ) : null}
-        </>
-      ) : null}
-    </ContentArea>
+    <SiblingBorder>
```
Comment (maxyinger) [inline packages/story-editor/src/components/panels/document/taxonomies/HierarchicalTermSelector.js]: Adding the wrapper is the only change here

File: packages/story-editor/src/components/panels/document/taxonomies/shared.js [hunk 2]
```diff
@@ -57,8 +57,18 @@ export const LinkButton = styled(Button).attrs({
...
+
+  & + & {
+    border-top: 1px solid ${({ theme }) => theme.colors.divider.tertiary};
+    padding-top: 16px;
+  }
+`;
+
 export const WordCloud = {
-  Heading: styled(ContentHeading)`
+  Heading: styled(ContentHeading).attrs({ as: 'h4' })`
```
Comment (BrittanyIRL) [inline packages/story-editor/src/components/panels/document/taxonomies/shared.js:72]: 🎉

**Review by BrittanyIRL — COMMENTED** [review]
I feel like the border should be assigned in `taxonomies.js` so that if there's more than just the default taxonomies additional borders will show up regardless of if, say, two custom taxonomies are added and they're both freeform. Thoughts?

**Comment by maxyinger** [comment]
> I feel like the border should be assigned in taxonomies.js so that if there's more than just the default taxonomies additional borders will show up regardless of if, say, two custom taxonomies are added and they're both freeform. Thoughts?

Yea that might make it a little more transparent. I can update to wrap them both in `taxonomies.js` vs in the components themselves

**Review by samwhale — APPROVED** [review]
The styling looks great except one thing:

Seems like line under a free form input is a little too close if there's a hierarchical input under it:

**Review by BrittanyIRL — APPROVED** [review]
🕺  🚀  Thanks for moving this! LGTM

File: packages/story-editor/src/components/form/hierarchical/index.js [hunk 3]
```diff
@@ -202,6 +202,7 @@ const HierarchicalInput = ({
         onChange={handleInputChange}
         label={label}
         type="search"
+        placeholder={__('search', 'web-stories')}
```
Comment (swissspidy) [inline packages/story-editor/src/components/form/hierarchical/index.js]:
```suggestion
        placeholder={__('Search', 'web-stories')}
```
