### PR TITLE
Bugfix:  Stuck Swatch Tooltips in Safari

### LINKED ISSUE #9188: Color Tooltips get stuck on screen in Safari
## Bug Description

On Safari, the color tooltips ("Gradients not allowed for text") sometimes get stuck on the screen. Seems to happen on mouse-out with high speed.

image17

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

Sometimes in safari this would happen: 
https://user-images.githubusercontent.com/58738530/135152882-c6aba1cb-0fad-4cd4-b5af-9307e84aa656.gif 

## Summary

Where disabled swatch tooltips (gradients for text elements, for example) would get stuck open. Only happens in Safari. Only happens on the color swatches. 

## Relevant Technical Choices

So, after doing some digging it appears that the `disabled` button `Swatch` elements in Safari were swallowing up the pointer event and preventing the `Tooltip`'s `onPointerLeave` from firing (sometimes, not every time). It feels likely that this is due to the 💅  fancy styles happening to get the swatches to look right - with various pseudo classes. This is solved by adding `pointer-events: none` to both the button when it's disabled and also the `:after` pseudo class for buttons that are enabled.  As it's only a problem in the swatch it felt better to solve for this at the swatch level rather than impact the whole tooltip - especially since it would mean swapping to a less performant event set for tracking the cursor. 

While in there trying to figure out what was going on I added in some swatches wrapped in tooltips to storybook, decided to leave them for testing/debugging. Also noticed some redundant props/styles so took those out. 

## User-facing changes

Now in Safari if you hover over some disabled color swatches they should close when you are no longer hovering on the swatch. 

safari swatch tooltips

## Testing Instructions

Verify that the swatch tooltips don't get stuck open any more.

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9188

### CODE REVIEW

**Review by miina — APPROVED** [review]
⭐  Thanks for the cleanup!

**Review by maxyinger — APPROVED** [review]
😎

**Review by BrookeGraham — APPROVED** [review]
🛸

File: packages/design-system/src/components/swatch/swatch.js [hunk 1]
```diff
@@ -61,12 +61,16 @@ const SwatchButton = styled.button.attrs({ type: 'button' })`
     css`
       opacity: 0.4;
       cursor: default;
+      /* pointer-events none here fixes an edge case in Safari when swatch is within a tooltip #9188 */
+      pointer-events: none;
```
Comment (samwhale) [inline packages/design-system/src/components/swatch/swatch.js:65]: noice

**Review by samwhale — APPROVED** [review]
noice!
