### PR TITLE
Media Library: Remove `aria-label` from image and video

### LINKED ISSUE #7574: Media Library: Incorrect use of `aria-label`
## Bug Description

Images and videos in the media library incorrectly have `aria-label` attributes.

Both should only have `alt` attributes.

Offending code:

https://github.com/google/web-stories-wp/blob/4c891bd2b6b10815c72b06d7bbccd15718da79b1/assets/src/edit-story/components/library/panes/media/common/innerElement.js#L135-L167

## Expected Behaviour

No usage of `aria-label`. Just `alt`

## Screenshots

Screenshot 2021-05-18 at 23 14 35

Screenshot 2021-05-18 at 23 14 15

## Additional Context

- Plugin Version: 1.7
- WordPress Version: 5.7
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

* Remove the two `aria-label` props in the code section shared above

### PR DESCRIPTION
**Pull request by samwhale**
## Summary

Remove the `aria-label` attribute from the image and video tags. Instead use:
* `alt` for `<image />`
* `title` for `<video />`

## Relevant Technical Choices

n/a

## To-do

n/a

## User-facing changes

n/a

**Image:**

**Video:**
 

**GIF:**

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Open dev tools
2. View an element in the media panel (media 3p works the best because they all have lots of attributes)
3. Inspect the `img` or `video` element that is rendered. Should not see `aria-label`. Should see `alt` for an `img` and `title` for a video.

### Does this PR have a security-related impact?

no

### Does this PR change what data or activity we track or use?

no

### Does this PR have a legal-related impact?

no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7574

### CODE REVIEW

File: packages/story-editor/src/components/library/test/mediaElement.js [hunk 1]
```diff
@@ -17,7 +17,7 @@
 /**
  * External dependencies
  */
-import { fireEvent } from '@testing-library/react';
+import { fireEvent, screen } from '@testing-library/react';
```
Comment (swissspidy) [inline packages/story-editor/src/components/library/test/mediaElement.js:20]: Some aXe coverage for these tests would be nice (`toHaveNoViolations`)

Comment (samwhale) [reply packages/story-editor/src/components/library/test/mediaElement.js:20]: can do!

File: packages/story-editor/src/components/library/test/mediaElement.js [hunk 2]
```diff
@@ -69,122 +92,92 @@ const renderMediaElement = (resource, providerType, canEditMedia = true) => {
...
+          ...resource,
+          local,
+        },
+        'local'
+      );
+
+      const results = await axe(container);
+      expect(results).toHaveNoViolations();
+    }
+  );
```
Comment (samwhale) [inline packages/story-editor/src/components/library/test/mediaElement.js]: 💭 Probably don't need one of these for each resource type and whether or not it's uploaded. Can remove the `it.each` if we just want one check.

Comment (swissspidy) [reply packages/story-editor/src/components/library/test/mediaElement.js]: I don't think `local` is relevant here, so I'd remove that from the table.

But I'd add a gif element to the list.

**Comment by BrittanyIRL** [comment]
🤔  these karma failures seem like they might be residual from these updates, are they?

**Review by BrittanyIRL — APPROVED** [review]
🕺

**Review by swissspidy — APPROVED** [review]
