### PR TITLE
E2E Tests: Reduce screenshot flakiness

### LINKED ISSUE #8793: E2E Tests: flakey screenshots due to carousel page previews
## Bug Description

Sometimes the screenshot is taken, before the pages of the story is preview, generating a different screenshot sometimes, see screenshots. We should wait until these pages load before taking screenshot. 

[Example](https://percy.io/google/web-stories-wp-e2e/builds/12110659/changed/682131647?browser=chrome&browser_ids=14%2C16&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=original&width=1600&widths=1600). 

## Screenshots

885fd2583a3763c06e5cea0b80e96324a51fc06e8492f2595d4714251e80c24d
cf74e46f9edd2b3ab0368f6ee517c4cf348dce9a0b142e7ebef2e79232a8fc70

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

There are lots of Percy screenshots constantly changing due to flakiness, even though there were no changes to those parts. That makes them unreliable.

## Summary

This PR removes some unnecessary screenshots and also tries to reduce flakiness by waiting a tad longer in some cases.

## Relevant Technical Choices

--

## To-do

Testing

## User-facing changes

None

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Verify Percy snapshots

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #8793

### CODE REVIEW

File: packages/e2e-tests/src/specs/wordpress/getStartedStory.js [hunk 1]
```diff
@@ -49,6 +57,14 @@ describe('Get Started Story', () => {
...
       );
 
+      // Wait for skeleton thumbnails in the carousel to render before taking a screenshot.
+      await page.waitForFunction(
+        () =>
+          !document.querySelector(
+            'li[data-testid^="carousel-page-preview-skeleton"]'
+          ),
+        { timeout: 5000 } // requestIdleCallback in the carousel kicks in after 5s the latest.
+      );
```
Comment (spacedmonkey) [inline packages/e2e-tests/src/specs/wordpress/getStartedStory.js:67]: Worth making this into a util?

**Review by spacedmonkey — APPROVED** [review]
Approved with a nicpic

File: packages/e2e-tests/src/specs/wordpress/getStartedStory.js (hunk 1 above)
Comment (swissspidy) [reply packages/e2e-tests/src/specs/wordpress/getStartedStory.js:67]: Yeah probably eventually. I wanna first see how well it works over time, how stable it is.
