### PR TITLE
Pre-Publish Checklist: Fix double scrollbars

### LINKED ISSUE #9404: Pre-Publish Checklist Double Scrollbars
## Bug Description

In the pre-publish checklist, when there are a few warnings, there can be some double scrollbars. That looks a bit odd and would be nice to fix.

## Expected Behaviour

No double scrollbars :-)

## Steps to Reproduce

Create a story that causes some warnings to pop up in the checklist.

## Screenshots

Screenshot 2021-10-11 at 10 59 43

## Additional Context

- Plugin Version: 1.13.0
- WordPress Version: 5.8
- Operating System: macOS
- Browser: Chrome

### PR DESCRIPTION
**Pull request by samwhale**
## Context

Double scrollbars are not cool.

## Summary

Only show one scrollbar if content is scrollable in the pre-publish checklist.

## Relevant Technical Choices

n/a

## To-do

n/a

## User-facing changes

|Before|After|
|--|--|
|double-scrollbars|single-scrollbar|

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Open editor
2. Add stuff to the story until you get many issues in the checklist
3. Open the checklist
4. Should not be double scrollbars. Double check by shrinking the height of the screen to force hidden double scrollbars to appear (if there were any).

### Does this PR have a security-related impact?

no

### Does this PR change what data or activity we track or use?

no

### Does this PR have a legal-related impact?

no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9404

### CODE REVIEW

File: packages/story-editor/src/components/tablist/styles.js [hunk 1]
```diff
@@ -138,11 +138,12 @@ export const PanelWrapper = styled.div`
         }
       }
 
-      * ${TabPanel} {
+      ${ScrollableContent} {
         height: 560px;
-        padding: 0 0 16px 16px;
-        overflow-y: scroll;
```
Comment (samwhale) [inline packages/story-editor/src/components/tablist/styles.js:144]: 🤕

**Review by maxyinger — APPROVED** [review]

**Review by BrittanyIRL — APPROVED** [review]
😻
