### PR TITLE
Pre-Publish Checklist: Add check for missing publisher logo

### LINKED ISSUE #9320: PPC: No Publisher Logos Check
@swissspidy pointed out that the issue that shows in the prepublish checklist when users have no publisher logos yet is incorrect - showing that they need to increase the size of the logo rather than just add a new one. 

Let's add a check for a publisher logo existing in a story before telling the user they need to make it larger. 
If there is no publisher logo let's display `Add a publisher logo to your story` that when clicked takes you to the publisher logo upload button. The helper text can stay the same as for increasing the size.

### PR DESCRIPTION
**Pull request by samwhale**
## Context

The "publisher logo too small" check was showing when there was no publisher logos

## Summary

Adds a publisher logo existence card to the checklist and prevents the 'publisher logo too small' card from showing.

## Relevant Technical Choices

n/a

## To-do

n/a

## User-facing changes

existence

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Delete all of the publisher logos in your app. This can be done by running `npm run env:reset-site` (which blows up everything) or deleting the media one by one from the media library

2. Create a new story from a template (easiest since it has a lot of pages)
3. Open the checklist. See the new card in the priority section
4. Click the card - should highlight the publisher logo section like in the gif

### Does this PR have a security-related impact?

no

### Does this PR change what data or activity we track or use?

no

### Does this PR have a legal-related impact?

no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9320

### CODE REVIEW

File: packages/story-editor/src/components/checklist/checklistContent/accessibilityChecks.js [hunk 1]
```diff
@@ -46,7 +46,7 @@ function AccessibilityPanel({
   return isChecklistMounted ? (
     <StyledTablistPanel
       badgeCount={badgeCount}
-      isExpanded={badgeCount && isOpen}
+      isExpanded={Boolean(badgeCount) && isOpen}
```
Comment (samwhale) [inline packages/story-editor/src/components/checklist/checklistContent/accessibilityChecks.js:49]: Proptype was failing because `badgeCount` is a number. When it is `0` then isExpanded is not a boolean

File: packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+ */
+import { useStory } from '../../../app';
+import { states, useHighlights } from '../../../app/highlights';
+import { ChecklistCard, ChecklistCardStyles } from '../../checklistCard';
+import { PRIORITY_COPY } from '../constants';
+import { useRegisterCheck } from '../countContext';
+import { useIsChecklistMounted } from '../popupMountedContext';
+
+export function publisherLogoExistence(publisherLogo) {
+  return !(publisherLogo?.id || publisherLogo?.url);
```
Comment (BrittanyIRL) [inline packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js]: Since a publisher logo can have an id of 0, let's make sure that's not returning true and showing this check. 
(reset site and uploaded 1 logo)
Screen Shot 2021-10-07 at 3 37 39 PM

(publisherLogo logged before return)
Screen Shot 2021-10-07 at 3 40 09 PM

**Review by BrittanyIRL — CHANGES_REQUESTED** [review]
Thanks for whipping this up so fast! 

Needs a little extra check for when the logo id is 0, then i think it's good!

File: packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js (hunk 2 above)
Comment (BrittanyIRL) [inline packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js]:
```suggestion
  return Boolean(publisherLogo?.id || publisherLogo?.url);
```

This will fix it

**Comment by spacedmonkey** [comment]
SGTM

File: packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js (hunk 2 above)
Comment (samwhale) [reply packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js]: I thought publisher logos couldn't have an id of zero 🤔 

So to make sure we don't have one, should we just check that there's no url, no height, and no width? Since `id === 0` doesn't guarantee that there's no publisher logo?

Comment (swissspidy) [reply packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js]: I think what Brittany is saying that right now when there is no publisher logo we return an "empty" object with `id === 0` instead of `null`. Something we're probably going to change.

Checking for something like `const hasPublisherLogo = Boolean(publisherLogo?.id)` should be enough

Comment (samwhale) [reply packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js]: >Checking for something like const hasPublisherLogo = Boolean(publisherLogo?.id) should be enough

Currently if there is no publisher logo then the publisher logo on in the story context is `{ id: 0, height: 0, width: 0, url: '' }`, so the `hasPublisherLogo` check would always be true.

Once the stored 'empty state' of the publisher logo changes to `null` that will work but for now I think it needs to check if the id is `0`, no? Unless I'm just having major Friday brain

Comment (swissspidy) [reply packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js]: > Once the stored 'empty state' of the publisher logo changes to null that will work but for now I think it needs to check if the id is 0, no?

If you coerce `0` to a `boolean` it will be `false`. Just what we want.

```js
const publisherLogo = { id: 0 }
const hasPublisherLogo = Boolean(publisherLogo?.id) // this will be false. exactly what we want.
```

File: packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js [hunk 3]
```diff
@@ -0,0 +1,72 @@
...
+import { useStory } from '../../../app';
+import { states, useHighlights } from '../../../app/highlights';
+import { ChecklistCard, ChecklistCardStyles } from '../../checklistCard';
+import { PRIORITY_COPY } from '../constants';
+import { useRegisterCheck } from '../countContext';
+import { useIsChecklistMounted } from '../popupMountedContext';
+
+export function publisherLogoExistence(publisherLogo) {
+  return !publisherLogo?.url && !publisherLogo?.height && !publisherLogo?.width;
+}
```
Comment (swissspidy) [inline packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js]:
```suggestion
export function publisherLogoExistence(publisherLogo) {
  return !(publisherLogo?.id);
}
```

Comment (swissspidy) [reply packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js]: Also, FWIW, this function checks whether the logo is **missing**, but the function is named publisherLogo_Existence_. That is super confusing.

Either rename this to `publisherLogoInexistence` (which is also confusing), or reverse the check:

```suggestion
/**
 * Determines whether a publisher logo exists.
 * @param {Object} publisherLogo Publisher logo object.
 * @return {boolean} Whether a publisher logo exists.
 */
export function publisherLogoExistence(publisherLogo) {
  return Boolean(publisherLogo?.id);
}
```

Of course update `PublisherLogoExistence` below accordingly

File: packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js (hunk 2 above)
Comment (swissspidy) [reply packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js]: No need for the `url` check really. Just checking for the ID is enough.

Comment (samwhale) [reply packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js]: Oh wait we're saying the same thing 😮‍💨 okay, it should be updated correctly now.

File: packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js (hunk 3 above)
Comment (BrittanyIRL) [reply packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js]: +1 for `PublisherLogoMissing`

**Review by maxyinger — APPROVED** [review]

File: packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js (hunk 3 above)
Comment (samwhale) [reply packages/story-editor/src/components/checklist/checks/publisherLogoExistence.js]: Ah good shout

**Review by BrittanyIRL — APPROVED** [review]
👍
