### PR TITLE
Taxonomy: Tighten up freeform input

### LINKED ISSUE #9281: Taxonomy: Tag Input Height Resize
## Bug Description

Found by @barklund in bugbash
> Slight difference in size for tag input height with and without tags in it (obvious when you undo/redo adding a single tag) 

## Expected Behaviour

Input should not resize until tags wrap

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### LINKED ISSUE #9291: Taxonomies: Reduce tag input size
## Feature Description

The input field for entering tags is **enormous**

Any chance we could make that a bit smaller? Usual input fields in the editor are more like ~36px in size, but this one is a whopping 54px.

Screenshot 2021-10-05 at 23 53 33

cc @aaskedall

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

Feedback from bugbash/initial team usage that the freeform (tag) input is a bit fat and could be tightened up to be more inline with the other input heights. 

## Summary

Keeps the initial freeform input at 36px, like our other 1 line inputs. When it needs to wrap it'll grow but until then it stays put - no more little height shift. 

## Relevant Technical Choices

Just height, margin, padding tweaks to get the input and the tags to play nicely together. 

## User-facing changes

| New | Old | 
| --- | --- | 
| Screen Shot 2021-10-07 at 2 30 55 PM | Screen Shot 2021-10-07 at 2 42 32 PM | 
| Screen Shot 2021-10-07 at 2 33 22 PM | Screen Shot 2021-10-07 at 2 43 08 PM| 
| Screen Shot 2021-10-07 at 2 31 04 PM | Screen Shot 2021-10-07 at 2 41 49 PM | 

## Testing Instructions

Verify there's no height jump after adding the initial tag to the input 

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9281 
Fixes #9291

### CODE REVIEW

File: packages/story-editor/src/components/form/tags/tag.js [hunk 1]
```diff
@@ -58,16 +58,17 @@ const Token = styled.span`
   position: relative;
   display: flex;
   align-items: center;
-  padding: 3px 2px;
-  margin: 3px 5px 3px 0;
-  max-width: calc(100% - 16px);
+  padding: 2px;
+  margin: 2px 4px;
```
Comment (maxyinger) [inline packages/story-editor/src/components/form/tags/tag.js]: can honestly probably tighten this even more to 2px all around like `margin: 2px;` just so all the gutters are the same size:
Screen Shot 2021-10-08 at 1 24 29 PM



Fine as is too tho

**Review by maxyinger — APPROVED** [review]

File: packages/story-editor/src/components/form/tags/tag.js (hunk 1 above)
Comment (BrittanyIRL) [reply packages/story-editor/src/components/form/tags/tag.js]: good call

Comment (BrittanyIRL) [reply packages/story-editor/src/components/form/tags/tag.js]: Screen Shot 2021-10-08 at 12 29 03 PM
